### ISSUE TITLE
Not opening in webos 6.10.30

### ISSUE THREAD

**Issue by adriadam10** [WillinuX-Code/webos-tvheadend#21]
I have installed it the through developer mode but can't be opened.

**Comment by Informatic** [comment]
Software Version 06.10.30 = webOS 3.9.2

**Comment by WillinuX-Code** [comment]
I don't own a tv using webos 3.x but I'm able to reproduce the error using the LG WebOS TV Emulator 3.0.0. 
It has been working before so I'm confident that a fix is possible. I'll keep you updated.

**Comment by WillinuX-Code** [comment]
Update: 
* The root cause seems to be a polyfill/transpile problem when using react-scripts
* Solution is to migrate from react-scripts to webpack
* From the first draft I'm now able to see the settings screen but after entering the connection url etc and clicking on save the screen goes black again
* debugging shows following error which seems to be caused by "Promise" not correctly polyfilled
* <img width="582" alt="Bildschirm­foto 2023-03-16 um 00 36 43" src="https://user-images.githubusercontent.com/77215257/225467357-7805399e-df80-4643-a99f-d7fcb0b7db7f.png">
* to be continued...

**Comment by WillinuX-Code** [comment]
Hey,

finally I got a workaround for the "Cannot read property 'then' of undefined" error.
Turns out the videoelement (or mediaelement in general) on webos 3.x doesn't return a promise, thats why we ran into this error.

This now fixed and release 0.8.1 is on its way :-)

**Comment by WillinuX-Code** [comment]
@Sudupe and @adriadam10 please verify if the app is now working correctly so I can close this issue.

**Comment by Sudupe** [comment]
Now it’s working. Thanks

**Comment by ivonovak** [comment]
Not working in WebOS7 . On WebOS 6 TVH same version is working perfect.
![IMG_0549](https://user-images.githubusercontent.com/724284/227004859-0cadcdbe-06a3-4cbb-9b1b-6e6897ad8168.jpg)

**Comment by WillinuX-Code** [comment]
> Not working in WebOS7, cannot connect to TVH server . On WebOS 6 TVH same version is working perfect.
> 
> ![IMG_0549](https://user-images.githubusercontent.com/724284/227004859-0cadcdbe-06a3-4cbb-9b1b-6e6897ad8168.jpg)
> 
> 

This indicates that the backen node service is not running. I will try to reproduce this using the WebOS 7 Simulator. Will get back once I got some news...

**Comment by darkcheater** [comment]
I can also help and provide logs if you tell me how I can do that :)

**Comment by GodHunter** [comment]
Same issue as @adriadam10 the screen turns black and the app doesnt start. The Splash Screen at the beginning is visible for me Software Version 6.10.30

Hopefully you can fix that issue, really nice work so far. Love the design

**Comment by efschu** [comment]
Not working for 3.4.0

**Comment by misery** [comment]
Same problem... splashscreen is visible. After that it switches to black.

Device: OLED48C38LA
Firmware: 0.3.11.45
webOS: 8.1.0

**Comment by robyevolution** [comment]
> Modifica: dopo aver aspettato molto a lungo, ottengo lo stesso errore di@ivonovak. Lo stesso account funziona all'interno di KODI, quindi le autorizzazioni non sono il problema. --- vecchio commento qui sotto:
> 
> Ciao, grazie per il software. Ho una TV webos 7.3.0 (OLED77B29LA). L'app si apre normalmente ma quando inserisco l'URL e il nome utente TVH (non ho ancora impostato una password) e faccio clic su Connetti, si carica all'infinito e non succede nulla :( ![foto1679599071](https://user-images.githubusercontent.com/15660491/227324854-daf63ca4-98da-4f2c-8911-842348b4c72b.jpeg)

Ho anchio questo problema, uscirà un aggiornamento per risolvere il problema?

**Comment by WillinuX-Code** [comment]
just released version 0.8.3 which is based on a different compile mechanism. Can you check if the errors still occur?

**Comment by misery** [comment]
Tried the 0.8.3 but the screen is still black after splashscreen.

**Comment by robyevolution** [comment]
same previous error

**Comment by WillinuX-Code** [comment]
1) Problem - app crash after splashscreen
Can someone open Web OS Dev Manager and make sure its connected and syslog is available. Start with a clean install, open the app and provide the syslogs for "com.willinux.tvh" from WebOS Dev Manager here?

2) Problem - com.willinux.tvh.app.proxy is not running
Can someone open Web OS Dev Manager and make sure its connected and syslog is available. Start with a clean install, open the app and provide the syslogs for "com.willinux.tvh" from WebOS Dev Manager here?

**Comment by WillinuX-Code** [comment]
unfortunately there is nothing related to the "proxy" service not running in the logs. Can you check what happens if you call the proxy service from command line?
This is the command: please adjust the tvheadend user and password (if required)

`luna-send -n 1 -f luna://com.willinux.tvh.app.proxy/proxy '{ "url": "http://userver.fritz.box:9981/api/serverinfo", "user": "myUser", "password": "***"}'`

This is the response I see
```
{
    "statusCode": 200,
    "result": "{\"sw_version\":\"4.3-2106~g9e1eb89be-dirty\",\"api_version\":19,\"name\":\"Tvheadend\",\"capabilities\":[\"caclient\",\"tvadapters\",\"satip_client\",\"satip_server\",\"timeshift\",\"trace\",\"libav\",\"caclient_advanced\"]}",
    "returnValue": true
}
```

**Comment by MartB** [comment]
Also running into this on my G2, endless loading

**Comment by manuelrn** [comment]
```
Device: OLED65E7V-Z
Firmware version: 06.10.30
webOS version: 3.9.0
Rooted: Unrooted
```

I have installed TVheadend Client for the first time (never used it before), and I have the same problem that several users mentioned above: TVheadend Client opens and displays the splash screen, but after finishing the splash screen it changes to black screen and stays like this (black screen) indefinitely.

I don't have my TV rooted or anything like that, I just enabled developer mode, connected to the TV with webOS Dev Manager and installed TVheadend Client.


Can I see the log somehow?
I have searched all the sections of webOS Dev Manager and I have not found anything to see a log or something like that.

I also tried to access the URL IP_TV:9998 and I got a list of Apps, I clicked on TVheadend and it showed me the following:
`<noscript>You need to enable JavaScript to run this app.</noscript>`
But I have no idea if this "error" is the fault of my TV or the fault of my PC's web browser.

It would be great if you can fix it @WillinuX-Code
Thank you very much!

**Comment by darkcheater** [comment]
@WillinuX-Code: I ran the command on my TV (didn't start the TVH app on the TV) and after some minutes, I get the following response:
` # luna-send -n 1 -f luna://com.willinux.tvh.app.proxy/proxy '{ "url": "http://
192.168.1.150:9981/api/serverinfo", "user": "lgtv", "password": "***"}
'
{
    "serviceName": "com.willinux.tvh.app.proxy",
    "returnValue": false,
    "errorText": "com.willinux.tvh.app.proxy is not running.",
    "errorCode": -1
}
LUNASERVICE ERROR -1: Could not cancel to unknown client (_LSTransportAddPendingMessageWithToken @ transport.c:4125)
`

**Comment by dm-rostov** [comment]
Tried the 0.8.3 but the screen is still black after splashscreen.  No diallog setup.
TV root

# luna-send -n 1 -f luna://com.willinux.tvh.app.proxy/proxy '{ "url": "http://192.168.1.50:9981/api/serverinfo", "user": "******", "password": "******"}'
{
    "statusCode": 200,
    "result": "{\"sw_version\":\"4.3-1054~g1d2374ae6\",\"api_version\":19,\"name\":\"Tvheadend\",\"capabilities\":[\"caclient\",\"tvadapters\",\"satip_client\",\                             "satip_server\",\"imagecache\",\"trace\",\"libav\"]}",
    "returnValue": true
}

**Comment by MartB** [comment]
Upgraded the entire project and changed some keepalive settings and it works for me now.
Will push my fork later. Thats a clear case of "I made it work for me". Not sure if this breaks a million other things.

**Comment by darkcheater** [comment]
Hey @MartB,
Whats the easiest way to install your fork on the TV?

**Comment by MartB** [comment]
> Hey @MartB, Whats the easiest way to install your fork on the TV?

Here you go, please report back https://github.com/MartB/webos-tvheadend/releases

**Comment by VDRrulez** [comment]
@MartB
Thanks alot. Works on my C2.

Webos 7.3.1-42

**Comment by manuelrn** [comment]
> Upgraded the entire project and changed some keepalive settings and it works for me now. Will push my fork later. Thats a clear case of "I made it work for me". Not sure if this breaks a million other things.
> 
> See here: https://github.com/MartB/webos-tvheadend/tree/tvh-g2
> 
> Contains a few changes unrelated to the issues that i wanted to try, should be easy to exclude.

With that release my problem is still present.

My problem was mentioned here above:
TVheadend Client opens and displays the splash screen, but after finishing the splash screen it changes to black screen and stays like this (black screen) indefinitely.

**Comment by ivonovak** [comment]
@MartB 
Now it Works on my C2, WebOS 7.3.x , but no EPG

**Comment by WillinuX-Code** [comment]
> Upgraded the entire project and changed some keepalive settings and it works for me now. Will push my fork later. Thats a clear case of "I made it work for me". Not sure if this breaks a million other things.
> 
> See here: https://github.com/MartB/webos-tvheadend/tree/tvh-g2
> 
> Contains a few changes unrelated to the issues that i wanted to try, should be easy to exclude.

Thanks for your contribution. I checked your changes and also installed your release for a quick test on WebOS 4 

- I assume the keep alive will fix the "com.willinux.tvh.proxy not running" error on newer WebOS version so I will take it over
- The epg loading in one large request is can lead to problems on older tvs because of the large epg message, thats why I prefer a loading in chunks
- Something in the update is also breaking the app for me after splash screen - don't know if its the library updates, the big epg load or the preload="auto" change

**Comment by MartB** [comment]
> * I assume the keep alive will fix the "com.willinux.tvh.proxy not running" error on newer WebOS version so I will take it over
> 
Yep that should be the main fix.

> * The epg loading in one large request is can lead to problems on older tvs because of the large epg message, thats why I prefer a loading in chunks
>

I hit the max entries limit and the quickest fix was throwing the chunk loading out which worked for me haha

> * Something in the update is also breaking the app for me after splash screen - don't know if its the library updates, the big epg load or the preload="auto" change

The preload change shouldnt break anything, i just played with this for better initial video load performance. Did not work though.

Thanks again for providing this app and all the work you put in :)

**Comment by michaelarnauts** [comment]
I'm wondering what the current development workflow is. I know typescript and packaging a bit, but I'm new to WebOS.

I've bought a C3 with WebOS23, but it seems that there are no emulators anymore since WebOS 22, only simulators. If I understand it correctly, it seems this repo only supports to run it on an emulator or the real hardware, but not on a simulator?

I guess I have to modify the TVHDataService:constructor() as indicated in the README.md, but I don't see it using a LunaServiceAdapter there.

**Comment by Saibot882** [comment]
I also have a black screen.

LG OLED83G39LA
Firmware 03.30.73
webOS 8.3.0
TVheasend Client 0.8.3

**Comment by saxoloman** [comment]
> I also have a black screen.
> 
> LG OLED83G39LA Firmware 03.30.73 webOS 8.3.0 TVheasend Client 0.8.3

Are you using the MartB fork ?

**Comment by Saibot882** [comment]
Thanks for the tipp with the MarkB fork. 
Now, the connection screen is displayed but after i click to the connect button it shows the following:
![20240313_083014](https://github.com/WillinuX-Code/webos-tvheadend/assets/156290112/f936e441-2612-4226-ac2f-1323e5b35bb6)

Here are my settings on TVheadend:
![tvhe](https://github.com/WillinuX-Code/webos-tvheadend/assets/156290112/2f52bdee-566b-4d03-9ab4-83ee24bcb93e)
![tvh](https://github.com/WillinuX-Code/webos-tvheadend/assets/156290112/dac72b7b-a0d9-4bef-9021-b361a285846a)

What's wrong?

**Comment by manuelrn** [comment]
I commented on this months ago, but I am commenting again.

I have tested both @WillinuX-Code and @MartB version and both fail, in both the same failure occurs. There are other people in this thread who have also reported the same failure.
<br/>
```
Device: OLED65E7V-Z
Firmware version: 06.10.30
webOS version: 3.9.0
Rooted: Unrooted
```

I have installed TVheadend Client for the first time (never used it before), and I have the same problem that several users mentioned above: TVheadend Client opens and displays the splash screen, but after finishing the splash screen it changes to black screen and stays like this (black screen) indefinitely.

I don't have my TV rooted or anything like that, I just enabled developer mode, connected to the TV with webOS Dev Manager and installed TVheadend Client.
<br/>
It would be great if you can fix it @WillinuX-Code or @MartB. It would be greatly appreciated!
If you need me to look or check something on my TV just let me know or explain what I need to do.

Thank you very much!

**Comment by 4920441** [comment]
...is there anything new on this issue? WebOS Version 5.6.03 
excactly the same issues as   @manuelrn experiences  despite the difference I rooted my tv (long time ago)

any thoughts?

**Comment by vtashev** [comment]
> release

Thanks a lot @MartB !
Using your build and release I manage to start it and connect 
Device - OLED77C22LB
Firmware - 13.30.80
webOS version 8.3.0(webOs 23 if I'm not wrong)

One thing is missing thou:
text in EPG table and description in channel list(the from left side)
Perhaps It migth be character encoding, as my provider uses Windows CP 1251 (Eastern Europe-Bulgaria)

@MartB Is there easy fix for char.encoding?

**Comment by hirschbp** [comment]
I stumbled over this project and tried it on my TV:
```
Device: OLED65B7D-Z
Firmware version: 06.10.55
webOS version: 3.9.0
Rooted: Unrooted
```
I am having the same issue as others, that I can see the splash screen on startup and then only black.
I was able to setup a debugger and got an error message:
`Uncaught TypeError: undefined is not a function 
(resolution.js:529)`
This is from the `@enact` module.
The code in this line is:
`exports.config = config = Object.assign({}, configDefaults);`
This should be the very same issue as in https://github.com/WillinuX-Code/webos-tvheadend/issues/15 

I am a developer, but I am a novice with everything JavaScript/TypeScript and WebOS related. I might give it a try in the next few days, but I am unsure on how to approach this (other than maybe trying a different version of enact). Or maybe this helps anyone else with more expertise who can take it from here.

**Comment by manuelrn** [comment]
> I stumbled over this project and tried it on my TV:
> 
> ```
> Device: OLED65B7D-Z
> Firmware version: 06.10.55
> webOS version: 3.9.0
> Rooted: Unrooted
> ```
> 
> I am having the same issue as others, that I can see the splash screen on startup and then only black. I was able to setup a debugger and got an error message: `Uncaught TypeError: undefined is not a function (resolution.js:529)` This is from the `@enact` module. The code in this line is: `exports.config = config = Object.assign({}, configDefaults);` This should be the very same issue as in [#15](https://github.com/WillinuX-Code/webos-tvheadend/issues/15)
> 
> I am a developer, but I am a novice with everything JavaScript/TypeScript and WebOS related. I might give it a try in the next few days, but I am unsure on how to approach this (other than maybe trying a different version of enact). Or maybe this helps anyone else with more expertise who can take it from here.

Hi @hirschbp, were you able to find out or solve something?

As you are a developer it would be appreciated if you can take a look and get it fixed, as this problem has been around for years so there doesn't seem to be any interest in fixing it from the developers.

**Comment by WillinuX-Code** [comment]
Hi, I created a new version which should now support the newer webos versions. I tested it on the webos simulator which works fine. Can you please verify if its working for you? Please download the ipk and install it on your tv. Let me know if it works or not.

[0.9.0 release draft](https://github.com/WillinuX-Code/webos-tvheadend/releases/tag/0.9.0-draft)

**Comment by manuelrn** [comment]
> Hi, I created a new version which should now support the newer webos versions. I tested it on the webos simulator which works fine. Can you please verify if its working for you? Please download the ipk and install it on your tv. Let me know if it works or not.
> 
> [0.9.0 release draft](https://github.com/WillinuX-Code/webos-tvheadend/releases/tag/0.9.0-draft)

Hi @WillinuX-Code, thank you very much for the new version.

I just tested this new version and I am still having the same problem that I have already described in previous comments on this Issue: TVheadend Client opens and displays the splash screen, but after finishing the splash screen it changes to black screen and stays like this (black screen) indefinitely.


My details are as follows:
```
Device: OLED65E7V-Z
Firmware version: 06.10.45
webOS version: 3.9.2
Rooted: Unrooted
```


If you managed to fix it I would appreciate it very much, I have been waiting for a long time that someday I can get this TVheadend Client to run.

Best regards and thank you very much!

**Comment by WillinuX-Code** [comment]
The 0.9.0 fix adresses problems with WebOS 6+.  No changes für WebOS 3 so far.

**Comment by manuelrn** [comment]
> The 0.9.0 fix adresses problems with WebOS 6+. No changes für WebOS 3 so far.

Ok @WillinuX-Code, understood. I had misread and confused firmware version 6 with webOS, sorry.


And do you plan to try to fix it for webOS 3?

I'm sure many users would appreciate it.
In this Issue there are a few people that we have commented with this same webOS 3 problem.


Best regards and thanks in advance!

**Comment by WillinuX-Code** [comment]
Next version includes a small fix to hopefully keep the service active on webos 6+
And fixed startup crash on webos 3 - at least on emulator it works now

[0.9.1-draft](https://github.com/WillinuX-Code/webos-tvheadend/releases/tag/0.9.1-draft)

**Comment by manuelrn** [comment]
> Next version includes a small fix to hopefully keep the service active on webos 6+ And fixed startup crash on webos 3 - at least on emulator it works now
> 
> [0.9.1-draft](https://github.com/WillinuX-Code/webos-tvheadend/releases/tag/0.9.1-draft)

Thanks for the new version @WillinuX-Code.

Unfortunately the exact same problem as always is still occurring (after finishing the splash screen it changes to black screen and stays like this (black screen) indefinitely).

It's a pity, this time I was hoping that it would finally work.

If you come up with any new ideas I would be happy to try it out and see if we can make it work.

Thank you very much anyway!
Best regards.

**Comment by th0enix** [comment]
Please try my build: https://github.com/th0enix/webos-tvheadend/releases

**Comment by manuelrn** [comment]
> Please try my build: https://github.com/th0enix/webos-tvheadend/releases

Hi @th0enix,

I have tried your build and I have the same problem, it stays black screen indefinitely (although in this one no splash screen appears).

By the way, I have tried to update from Firmware 06.10.45 and webOS 3.9.2 to Firmware 06.10.60 and webOS 3.9.3, since this update was released a few days ago, but the same problem still occurs.


I have also tried the new Pre-release 0.9.2-draft from @WillinuX-Code, but the same problem still occurs.

Best regards and thank you very much for your efforts.

**Comment by th0enix** [comment]
You can debug the app by opening this link in chrome: chrome://inspect/#devices , click on configure and add: **<-TVIP->**:9998 . Now start the app and you can click on 'inspect'. This opens up a new DevTools window. Then click on the blue Smartphone/Tablet symbol and you can get to the 'Console' tab. Then just post the errors displayed and we can diagnose further.

**Comment by manuelrn** [comment]
> You can debug the app by opening this link in chrome: chrome://inspect/#devices , click on configure and add: **<-TVIP->**:9998 . Now start the app and you can click on 'inspect'. This opens up a new DevTools window. Then click on the blue Smartphone/Tablet symbol and you can get to the 'Console' tab. Then just post the errors displayed and we can diagnose further.

Thank you very much for helping @th0enix!

I just did it but the console doesn't show anything.... Is it necessary that the TV is rooted or do something?


Here I leave you some screenshots of how it looks (nothing is showing):
![Image](https://github.com/user-attachments/assets/451a3ce5-1f0a-4175-9c44-1ead321ee5c4)


I have also tried looking at the Elements tab and this appears:
![Image](https://github.com/user-attachments/assets/93a0c983-e898-45c2-86a8-5efe48d637cf)

The following text appears "You need to enable JavaScript to run this app.", I do not know if it will be something relevant? I guess not because I think that's just the HTML code of the web and it's not a log or anything like that.
<br />
<br />
I have also tried to do the same with @WillinuX-Code 's IPK file and it does not show me anything in the console either, although with this IPK the content of the Elements tab is different:
![Image](https://github.com/user-attachments/assets/faab9e51-3995-4f53-b465-e9e40adaed5c)
<br />
Let me know if you have any ideas, thank you very much!

**Comment by th0enix** [comment]
@manuelrn Please try to refresh the page on top left beside 'file:///'
I have an unrooted TV, just downloaded the Developer App.
You can also try to open up a webpage instead of 'file:///' and check if that webpage loads correctly

**Comment by hirschbp** [comment]
> Next version includes a small fix to hopefully keep the service active on webos 6+ And fixed startup crash on webos 3 - at least on emulator it works now
> 
> [0.9.1-draft](https://github.com/WillinuX-Code/webos-tvheadend/releases/tag/0.9.1-draft)

@WillinuX-Code I tried your draft version on my OLED65B7D and it unfortunately still only shows the splash screen and a black screen afterwards. I was able to attach a debugger which got me the following console output:
```
Not allowed to load local resource: file:///ilib/locale/ilibmanifest.json index.html:1
DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///ilib/locale/ilibmanifest.json'.code: 19message: "Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///ilib/locale/ilibmanifest.json'."name: "NetworkError"stack: "Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///ilib/locale/ilibmanifest.json'.↵    at Error (native)↵    at s (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:618365)↵    at l (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:616165)↵    at s (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:608465)↵    at c (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:608801)↵    at g._loadManifest (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:612527)↵    at g.loadManifestsSync (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:612831)↵    at g.<anonymous> (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:611418)↵    at Array.forEach (native)↵    at g.loadFiles (file:///media/developer/apps/usr/palm/applications/com.willinux.tvh.app/webos4/static/js/2.344ece0b.chunk.js:2:611198)"__proto__: DOMException 2.344ece0b.chunk.js:2eu 2.344ece0b.chunk.js:2
Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///ilib/locale/ilibmanifest.json'. 2.344ece0b.chunk.js:2

```

<img width="1849" height="312" alt="Image" src="https://github.com/user-attachments/assets/1665a6e1-9239-4fc8-b0c3-e31291a768f2" />
